package com.demo5.models;
// Generated 09/06/2018 12:58:59 PM by Hibernate Tools 4.3.1



/**
 * ComedorAlumno generated by hbm2java
 */
public class ComedorAlumno  implements java.io.Serializable {


     private int dniAlumno;
     private int codigoAlumno;
     private String nombresAlumno;
     private String apellidosAlumno;
     private String facultad;
     private String escuela;
     private int piso;
     private int turno;

    public ComedorAlumno() {
    }

	
    public ComedorAlumno(int dniAlumno, int codigoAlumno, int piso, int turno) {
        this.dniAlumno = dniAlumno;
        this.codigoAlumno = codigoAlumno;
        this.piso = piso;
        this.turno = turno;
    }
    public ComedorAlumno(int dniAlumno, int codigoAlumno, String nombresAlumno, String apellidosAlumno, String facultad, String escuela, int piso, int turno) {
       this.dniAlumno = dniAlumno;
       this.codigoAlumno = codigoAlumno;
       this.nombresAlumno = nombresAlumno;
       this.apellidosAlumno = apellidosAlumno;
       this.facultad = facultad;
       this.escuela = escuela;
       this.piso = piso;
       this.turno = turno;
    }
   
    public int getDniAlumno() {
        return this.dniAlumno;
    }
    
    public void setDniAlumno(int dniAlumno) {
        this.dniAlumno = dniAlumno;
    }
    public int getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(int codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }
    public String getNombresAlumno() {
        return this.nombresAlumno;
    }
    
    public void setNombresAlumno(String nombresAlumno) {
        this.nombresAlumno = nombresAlumno;
    }
    public String getApellidosAlumno() {
        return this.apellidosAlumno;
    }
    
    public void setApellidosAlumno(String apellidosAlumno) {
        this.apellidosAlumno = apellidosAlumno;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(String escuela) {
        this.escuela = escuela;
    }
    public int getPiso() {
        return this.piso;
    }
    
    public void setPiso(int piso) {
        this.piso = piso;
    }
    public int getTurno() {
        return this.turno;
    }
    
    public void setTurno(int turno) {
        this.turno = turno;
    }




}


